### PR TITLE
Added .gitignore file to prevent target/ files from appearing in staging...

### PR DESCRIPTION
**Pull request by juzerali**
its annoying to see files in git staging area after an mvn install

### CODE REVIEW

**Comment by BrianAker** [comment]
Thanks!

**Comment by juzerali** [comment]
@BrianAker You closed the issue but did not merge the commit.

**Comment by BrianAker** [comment]
I am very sorry about that. I thought I had.

It should be merged now.

**Comment by juzerali** [comment]
Cool

On Sat, Feb 15, 2014 at 5:36 PM, Brian Aker notifications@github.comwrote:

> I am very sorry about that. I thought I had.
> 
> It should be merged now.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/gearman/java-service/pull/2#issuecomment-35154581
> .

## 

Regards,
Juzer Ali
http://about.me/juzerali

**Pull request merged**
